// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package reacttoursample.proxies;

public class Helper
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject helperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "ReactTourSample.Helper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Steps("Steps"),
		StartTour("StartTour"),
		accentColor("accentColor"),
		CloseWithMaskValue("CloseWithMaskValue"),
		disabledotnavigation("disabledotnavigation"),
		disablekeyboardnavigation("disablekeyboardnavigation"),
		showbutton("showbutton"),
		showclosebutton("showclosebutton"),
		shownavigation("shownavigation"),
		shownavigationnumber("shownavigationnumber"),
		shownumber("shownumber"),
		StartAt("StartAt"),
		disablefocuslock("disablefocuslock");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Helper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Helper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject helperMendixObject)
	{
		if (helperMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, helperMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.helperMendixObject = helperMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Helper.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static reacttoursample.proxies.Helper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return reacttoursample.proxies.Helper.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static reacttoursample.proxies.Helper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new reacttoursample.proxies.Helper(context, mendixObject);
	}

	public static reacttoursample.proxies.Helper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return reacttoursample.proxies.Helper.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Steps
	 */
	public final java.lang.String getSteps()
	{
		return getSteps(getContext());
	}

	/**
	 * @param context
	 * @return value of Steps
	 */
	public final java.lang.String getSteps(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Steps.toString());
	}

	/**
	 * Set value of Steps
	 * @param steps
	 */
	public final void setSteps(java.lang.String steps)
	{
		setSteps(getContext(), steps);
	}

	/**
	 * Set value of Steps
	 * @param context
	 * @param steps
	 */
	public final void setSteps(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String steps)
	{
		getMendixObject().setValue(context, MemberNames.Steps.toString(), steps);
	}

	/**
	 * @return value of StartTour
	 */
	public final java.lang.Boolean getStartTour()
	{
		return getStartTour(getContext());
	}

	/**
	 * @param context
	 * @return value of StartTour
	 */
	public final java.lang.Boolean getStartTour(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.StartTour.toString());
	}

	/**
	 * Set value of StartTour
	 * @param starttour
	 */
	public final void setStartTour(java.lang.Boolean starttour)
	{
		setStartTour(getContext(), starttour);
	}

	/**
	 * Set value of StartTour
	 * @param context
	 * @param starttour
	 */
	public final void setStartTour(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean starttour)
	{
		getMendixObject().setValue(context, MemberNames.StartTour.toString(), starttour);
	}

	/**
	 * @return value of accentColor
	 */
	public final java.lang.String getaccentColor()
	{
		return getaccentColor(getContext());
	}

	/**
	 * @param context
	 * @return value of accentColor
	 */
	public final java.lang.String getaccentColor(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.accentColor.toString());
	}

	/**
	 * Set value of accentColor
	 * @param accentcolor
	 */
	public final void setaccentColor(java.lang.String accentcolor)
	{
		setaccentColor(getContext(), accentcolor);
	}

	/**
	 * Set value of accentColor
	 * @param context
	 * @param accentcolor
	 */
	public final void setaccentColor(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String accentcolor)
	{
		getMendixObject().setValue(context, MemberNames.accentColor.toString(), accentcolor);
	}

	/**
	 * @return value of CloseWithMaskValue
	 */
	public final java.lang.Boolean getCloseWithMaskValue()
	{
		return getCloseWithMaskValue(getContext());
	}

	/**
	 * @param context
	 * @return value of CloseWithMaskValue
	 */
	public final java.lang.Boolean getCloseWithMaskValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.CloseWithMaskValue.toString());
	}

	/**
	 * Set value of CloseWithMaskValue
	 * @param closewithmaskvalue
	 */
	public final void setCloseWithMaskValue(java.lang.Boolean closewithmaskvalue)
	{
		setCloseWithMaskValue(getContext(), closewithmaskvalue);
	}

	/**
	 * Set value of CloseWithMaskValue
	 * @param context
	 * @param closewithmaskvalue
	 */
	public final void setCloseWithMaskValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean closewithmaskvalue)
	{
		getMendixObject().setValue(context, MemberNames.CloseWithMaskValue.toString(), closewithmaskvalue);
	}

	/**
	 * @return value of disabledotnavigation
	 */
	public final java.lang.Boolean getdisabledotnavigation()
	{
		return getdisabledotnavigation(getContext());
	}

	/**
	 * @param context
	 * @return value of disabledotnavigation
	 */
	public final java.lang.Boolean getdisabledotnavigation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.disabledotnavigation.toString());
	}

	/**
	 * Set value of disabledotnavigation
	 * @param disabledotnavigation
	 */
	public final void setdisabledotnavigation(java.lang.Boolean disabledotnavigation)
	{
		setdisabledotnavigation(getContext(), disabledotnavigation);
	}

	/**
	 * Set value of disabledotnavigation
	 * @param context
	 * @param disabledotnavigation
	 */
	public final void setdisabledotnavigation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean disabledotnavigation)
	{
		getMendixObject().setValue(context, MemberNames.disabledotnavigation.toString(), disabledotnavigation);
	}

	/**
	 * @return value of disablekeyboardnavigation
	 */
	public final java.lang.Boolean getdisablekeyboardnavigation()
	{
		return getdisablekeyboardnavigation(getContext());
	}

	/**
	 * @param context
	 * @return value of disablekeyboardnavigation
	 */
	public final java.lang.Boolean getdisablekeyboardnavigation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.disablekeyboardnavigation.toString());
	}

	/**
	 * Set value of disablekeyboardnavigation
	 * @param disablekeyboardnavigation
	 */
	public final void setdisablekeyboardnavigation(java.lang.Boolean disablekeyboardnavigation)
	{
		setdisablekeyboardnavigation(getContext(), disablekeyboardnavigation);
	}

	/**
	 * Set value of disablekeyboardnavigation
	 * @param context
	 * @param disablekeyboardnavigation
	 */
	public final void setdisablekeyboardnavigation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean disablekeyboardnavigation)
	{
		getMendixObject().setValue(context, MemberNames.disablekeyboardnavigation.toString(), disablekeyboardnavigation);
	}

	/**
	 * @return value of showbutton
	 */
	public final java.lang.Boolean getshowbutton()
	{
		return getshowbutton(getContext());
	}

	/**
	 * @param context
	 * @return value of showbutton
	 */
	public final java.lang.Boolean getshowbutton(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.showbutton.toString());
	}

	/**
	 * Set value of showbutton
	 * @param showbutton
	 */
	public final void setshowbutton(java.lang.Boolean showbutton)
	{
		setshowbutton(getContext(), showbutton);
	}

	/**
	 * Set value of showbutton
	 * @param context
	 * @param showbutton
	 */
	public final void setshowbutton(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showbutton)
	{
		getMendixObject().setValue(context, MemberNames.showbutton.toString(), showbutton);
	}

	/**
	 * @return value of showclosebutton
	 */
	public final java.lang.Boolean getshowclosebutton()
	{
		return getshowclosebutton(getContext());
	}

	/**
	 * @param context
	 * @return value of showclosebutton
	 */
	public final java.lang.Boolean getshowclosebutton(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.showclosebutton.toString());
	}

	/**
	 * Set value of showclosebutton
	 * @param showclosebutton
	 */
	public final void setshowclosebutton(java.lang.Boolean showclosebutton)
	{
		setshowclosebutton(getContext(), showclosebutton);
	}

	/**
	 * Set value of showclosebutton
	 * @param context
	 * @param showclosebutton
	 */
	public final void setshowclosebutton(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showclosebutton)
	{
		getMendixObject().setValue(context, MemberNames.showclosebutton.toString(), showclosebutton);
	}

	/**
	 * @return value of shownavigation
	 */
	public final java.lang.Boolean getshownavigation()
	{
		return getshownavigation(getContext());
	}

	/**
	 * @param context
	 * @return value of shownavigation
	 */
	public final java.lang.Boolean getshownavigation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.shownavigation.toString());
	}

	/**
	 * Set value of shownavigation
	 * @param shownavigation
	 */
	public final void setshownavigation(java.lang.Boolean shownavigation)
	{
		setshownavigation(getContext(), shownavigation);
	}

	/**
	 * Set value of shownavigation
	 * @param context
	 * @param shownavigation
	 */
	public final void setshownavigation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean shownavigation)
	{
		getMendixObject().setValue(context, MemberNames.shownavigation.toString(), shownavigation);
	}

	/**
	 * @return value of shownavigationnumber
	 */
	public final java.lang.Boolean getshownavigationnumber()
	{
		return getshownavigationnumber(getContext());
	}

	/**
	 * @param context
	 * @return value of shownavigationnumber
	 */
	public final java.lang.Boolean getshownavigationnumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.shownavigationnumber.toString());
	}

	/**
	 * Set value of shownavigationnumber
	 * @param shownavigationnumber
	 */
	public final void setshownavigationnumber(java.lang.Boolean shownavigationnumber)
	{
		setshownavigationnumber(getContext(), shownavigationnumber);
	}

	/**
	 * Set value of shownavigationnumber
	 * @param context
	 * @param shownavigationnumber
	 */
	public final void setshownavigationnumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean shownavigationnumber)
	{
		getMendixObject().setValue(context, MemberNames.shownavigationnumber.toString(), shownavigationnumber);
	}

	/**
	 * @return value of shownumber
	 */
	public final java.lang.Boolean getshownumber()
	{
		return getshownumber(getContext());
	}

	/**
	 * @param context
	 * @return value of shownumber
	 */
	public final java.lang.Boolean getshownumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.shownumber.toString());
	}

	/**
	 * Set value of shownumber
	 * @param shownumber
	 */
	public final void setshownumber(java.lang.Boolean shownumber)
	{
		setshownumber(getContext(), shownumber);
	}

	/**
	 * Set value of shownumber
	 * @param context
	 * @param shownumber
	 */
	public final void setshownumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean shownumber)
	{
		getMendixObject().setValue(context, MemberNames.shownumber.toString(), shownumber);
	}

	/**
	 * @return value of StartAt
	 */
	public final java.lang.Integer getStartAt()
	{
		return getStartAt(getContext());
	}

	/**
	 * @param context
	 * @return value of StartAt
	 */
	public final java.lang.Integer getStartAt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.StartAt.toString());
	}

	/**
	 * Set value of StartAt
	 * @param startat
	 */
	public final void setStartAt(java.lang.Integer startat)
	{
		setStartAt(getContext(), startat);
	}

	/**
	 * Set value of StartAt
	 * @param context
	 * @param startat
	 */
	public final void setStartAt(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer startat)
	{
		getMendixObject().setValue(context, MemberNames.StartAt.toString(), startat);
	}

	/**
	 * @return value of disablefocuslock
	 */
	public final java.lang.Boolean getdisablefocuslock()
	{
		return getdisablefocuslock(getContext());
	}

	/**
	 * @param context
	 * @return value of disablefocuslock
	 */
	public final java.lang.Boolean getdisablefocuslock(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.disablefocuslock.toString());
	}

	/**
	 * Set value of disablefocuslock
	 * @param disablefocuslock
	 */
	public final void setdisablefocuslock(java.lang.Boolean disablefocuslock)
	{
		setdisablefocuslock(getContext(), disablefocuslock);
	}

	/**
	 * Set value of disablefocuslock
	 * @param context
	 * @param disablefocuslock
	 */
	public final void setdisablefocuslock(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean disablefocuslock)
	{
		getMendixObject().setValue(context, MemberNames.disablefocuslock.toString(), disablefocuslock);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return helperMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final reacttoursample.proxies.Helper that = (reacttoursample.proxies.Helper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
